# ── Required ──────────────────────────────────────────────────────────────────
genomes: "/Users/juliemcdonald/Documents/flamholz_lab/tri_strain_pilot/260616_quintara_RNAseq/260714_4_genome_analysis/genomes"

# ── Optional ──────────────────────────────────────────────────────────────────
threads: 8
